import yaml
import os
from pathlib import Path
from typing import List
from core.models import SkillDef, Department

class SkillGenerator:
    def __init__(self, base_output_dir: str = "knowledge_base"):
        self.base_output_dir = Path(base_output_dir)
        
    def generate_skill_md(self, skill: SkillDef, department: Department) -> str:
        # Create frontmatter
        frontmatter_dict = {
            "name": skill.name,
            "description": skill.description
        }
        if skill.license:
            frontmatter_dict["license"] = skill.license
        if skill.metadata:
            meta_dict = skill.metadata.model_dump(exclude_none=True, by_alias=True)
            if meta_dict:
                frontmatter_dict["metadata"] = meta_dict

        frontmatter = yaml.dump(frontmatter_dict, sort_keys=False, default_flow_style=False)
        
        # Build Markdown content
        md_content = f"---\n{frontmatter}---\n\n"
        
        md_content += "<!-- ⚠️ AUTO-GENERATED COGNITION PAYLOAD ⚠️ -->\n"
        md_content += "<!-- Do not edit this file directly. This skill was automatically provisioned from the Canonical Intelligence Layer. -->\n\n"
        
        md_content += f"# {skill.name.replace('-', ' ').title()}\n\n"
        
        md_content += f"## Overview\n{skill.overview}\n\n"
        
        if skill.prerequisites:
            md_content += "## Prerequisites\n"
            for prereq in skill.prerequisites:
                md_content += f"- {prereq}\n"
            md_content += "\n"
            
        if skill.steps:
            md_content += "## Step-by-step Instructions\n"
            for i, step in enumerate(skill.steps, 1):
                md_content += f"{i}. {step}\n"
            md_content += "\n"
            
        if skill.examples:
            md_content += "## Examples\n"
            for example in skill.examples:
                if "input" in example:
                    md_content += f"**Input:** {example['input']}\n"
                if "output" in example:
                    md_content += f"**Output:** {example['output']}\n"
                md_content += "\n"
                
        if skill.edge_cases:
            md_content += "## Edge Cases & What NOT to do\n"
            for edge_case in skill.edge_cases:
                md_content += f"- {edge_case}\n"
            md_content += "\n"
            
        return md_content

    def save_skill(self, skill: SkillDef, department: Department):
        dept_dir = self.base_output_dir / department.value / skill.name
        dept_dir.mkdir(parents=True, exist_ok=True)
        
        # Create standard directories
        (dept_dir / "scripts").mkdir(exist_ok=True)
        (dept_dir / "references").mkdir(exist_ok=True)
        (dept_dir / "assets").mkdir(exist_ok=True)
        
        skill_path = dept_dir / "SKILL.md"
        content = self.generate_skill_md(skill, department)
        
        with open(skill_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        return str(skill_path)

    def generate_context_md(self, skill: SkillDef, department: Department) -> str:
        """Generate a CONTEXT.md file for a department skill.

        CONTEXT.md contains the operational context that agents need when
        they're bound to this department — policies, decisions, failure
        patterns, security rules, and approval flows.

        This is read by AgentContextAssembler during context injection.
        """
        from datetime import datetime, timezone

        md = f"<!-- AUTO-GENERATED CONTEXT — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC -->\n"
        md += f"<!-- Department: {department.value} | Skill: {skill.name} -->\n\n"
        md += f"# {department.value.title()} — {skill.name.replace('-', ' ').title()} Context\n\n"

        # Overview section
        md += f"## Overview\n{skill.overview}\n\n"

        # Prerequisites as context constraints
        if skill.prerequisites:
            md += "## Operating Constraints\n"
            for prereq in skill.prerequisites:
                md += f"- {prereq}\n"
            md += "\n"

        # Edge cases as "Never do this" rules
        if skill.edge_cases:
            md += "## Critical Rules & Failure Patterns\n"
            for ec in skill.edge_cases:
                md += f"- ⚠️ {ec}\n"
            md += "\n"

        # Key steps as reference procedures
        if skill.steps:
            md += "## Reference Procedures\n"
            for i, step in enumerate(skill.steps[:10], 1):  # Cap at 10 for context brevity
                md += f"{i}. {step}\n"
            md += "\n"

        return md

    def save_context(self, skill: SkillDef, department: Department) -> str:
        """Write CONTEXT.md alongside the SKILL.md for a given department/skill."""
        dept_dir = self.base_output_dir / department.value / skill.name
        dept_dir.mkdir(parents=True, exist_ok=True)

        ctx_path = dept_dir / "CONTEXT.md"
        content = self.generate_context_md(skill, department)

        with open(ctx_path, "w", encoding="utf-8") as f:
            f.write(content)

        return str(ctx_path)
